pipeline {
    agent any
    tools {
        // These MUST match the names you set in Manage Jenkins > Tools
        jdk 'JAVA_21'
        maven 'MVN_3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build & Test') {
            steps {
                // 'dir' moves Jenkins into the folder where your pom.xml lives
                dir('exp3/my-app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Deploy to Tomcat') {
            steps {
                // This deploys the WAR to your Tomcat on port 8090
                dir('exp3/my-app') {
                    sh "curl -v -u admin:admin --upload-file target/*.war 'http://localhost:8090/manager/text/deploy?path=/my-demo&update=true'"
                }
            }
        }
        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'exp3/my-app/target/*.war', allowEmptyArchive: true
            }
        }
    }
}